GET http://localhost:1323/healthcheck

###
GET http://localhost:1323/beans

###

POST http://localhost:1323/beans
content-type: application/json

{
    "productionRegion": "エチオピア",
    "kind": "品種",
    "roastId": 1
}

###
GET http://localhost:1323/roast-levels