GET http://localhost:1323/healthcheck

###
GET http://localhost:1323/beans

###

POST http://localhost:1323/beans
content-type: application/json

{
    "productionArea": "エチオピア",
    "kind": "品種",
    "roastLevel": "浅煎り"
}