components:
  schemas:
    Recipe:
      required:
        - id
        - title
        - description
        - grindSizeId
        - extractionEquipment
        - coffeeType
        - waterTemperature
        - beanDose
        - steps
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        grindSizeId:
          type: integer
        extractionEquipment:
          type: string
        coffeeType:
          type: string
        waterTemperature:
          type: integer
        beanDose:
          type: integer
        steps:
          type: array
          items:
            $ref: "./RecipeStep.yml#/components/schemas/RecipeStep"
    CreateRecipe:
      type: object
      required:
        - title
        - description
        - grindSizeId
        - extractionEquipment
        - coffeeType
        - waterTemperature
        - beanDose
        - steps
      properties:
        title:
          type: string
        description:
          type: string
        grindSizeId:
          type: integer
        extractionEquipment:
          type: string
        coffeeType:
          type: string
        waterTemperature:
          type: integer
        beanDose:
          type: integer
        steps:
          type: array
          items:
            $ref: "./RecipeStep.yml#/components/schemas/CreateRecipeStep"
