openapi: 3.0.0
info:
  version: 0.0.1
  title: brew-note api
tags:
  - name: brew-note
    description: Brew Note 関連のAPI
paths:
  /me:
    $ref: ./paths/me/index.yml
  /users:
    $ref: ./paths/users/index.yml
  /beans:
    $ref: ./paths/beans/index.yml
