openapi: 3.0.0
info:
  version: 0.0.1
  title: tripig api
tags:
  - name: tripig
    description: Tripig 関連のAPI
paths:
  /tripig/search/nearby:
    $ref: ./paths/place/nearby.yml
  /tripig/users:
    $ref: ./paths/users/index.yml
