openapi: 3.0.0
info:
  version: 0.0.1
  title: coffee-paws api
tags:
  - name: coffee-paws
    description: Coffee Paws 関連のAPI
paths:
  /coffee-paws/places/nearby:
    $ref: ./paths/places/nearby.yml
  /coffee-paws/places/types:
    $ref: ./paths/places/types.yml
  /coffee-paws/users:
    $ref: ./paths/users/index.yml
  /coffee-paws/users/{id}:
    $ref: ./paths/users/id.yml
  /coffee-paws/stores:
    $ref: ./paths/stores/index.yml
