# Docker コンテナ -> Docker コンテナDBへのmigration
development:
  dialect: mysql
  dir: sql
  datasource: docker:docker@tcp(db:3306)/coffee_paws?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
  table: migrations

# Docker コンテナ -> ホストDBへのmigration
raspberry:
  dialect: mysql
  dir: sql
  datasource: migration:migration@tcp(host.docker.internal:3306)/coffee_paws?parseTime=true
  table: migrations

