development:
  dialect: mysql
  dir: sql
  datasource: docker:docker@tcp(db:3306)/coffee_paws?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
  table: migrations

test:
  dialect: mysql
  dir: sql
  datasource: docker:docker@tcp(db:3306)/coffee_paws?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
  table: migrations
