-- +migrate Up
CREATE TABLE IF NOT EXISTS `users` (
  `id` VARCHAR(255) NOT NULL COMMENT 'user_id',
  `name` VARCHAR(255) COMMENT 'user name',
  `nick_name` VARCHAR(255) COMMENT 'user nick name',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'create_date',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update_date',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT 'delete_date',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB COMMENT='user table';
CREATE TABLE IF NOT EXISTS `beans` (
  `id` VARCHAR(255) NOT NULL COMMENT 'beans id',
  `user_id` VARCHAR(255) COMMENT 'user name',
  `production_area` VARCHAR(255) NOT NULL COMMENT '産地',
  `kind` VARCHAR(255) NOT NULL COMMENT '品種',
  `roast_level` VARCHAR(255) NOT NULL COMMENT '焙煎度合い',
  `price_per_100g` VARCHAR(255) NOT NULL COMMENT '100g当たりの単価',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'create_date',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update_date',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT 'delete_date',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB COMMENT='bean table';
CREATE TABLE IF NOT EXISTS `recipes` (
  `id` VARCHAR(255) NOT NULL COMMENT 'recipes id',
  `user_id` VARCHAR(255) NOT NULL COMMENT 'user id',
  `step_number` VARCHAR(255) NOT NULL COMMENT 'ステップ数',
  `memo` VARCHAR(255) NOT NULL COMMENT 'メモ',
  `temperature` VARCHAR(255) NOT NULL COMMENT '温度',
  `seconds` VARCHAR(255) NOT NULL COMMENT '秒数',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'create_date',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update_date',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT 'delete_date',
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB COMMENT='recipe table';

-- +migrate Down
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `beans`;
DROP TABLE IF EXISTS `recipes`;